/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Datos.dPan;
import Logica.lEmpleados;
import Logica.lPan;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando
 */
public class fPan extends javax.swing.JFrame {

    /**
     * Creates new form fPan
     */
    public fPan() {
        initComponents();
        mostrar("");
        this.setTitle("Pan");
        habilitar();
        //pone la ventana en el Centro de la pantalla
        setLocationRelativeTo(null);
        setDefaultCloseOperation(fPrincipal.EXIT_ON_CLOSE);
    }

    private String accion = "Guardar";

    void inhabilitar() {
        jtb_id.setVisible(false);
        jtb_nombre.setVisible(false);
        jtb_clase.setVisible(false);
        jtb_cantidad.setVisible(false);

        jbot_nuevo.setEnabled(false);
        jbot_guardar.setEnabled(false);
        jbot_cancelar.setEnabled(false);
    }

    void habilitar() {
        jtb_id.setVisible(true);
        jtb_nombre.setVisible(true);
        jtb_clase.setVisible(true);
        jtb_cantidad.setVisible(true);

        jbot_nuevo.setEnabled(true);
        jbot_guardar.setEnabled(true);
        jbot_cancelar.setEnabled(true);
        jtb_nombre.setText("");
        jtb_id.setText("");
        jtb_nombre.setText("");
        jtb_clase.setText("");
        jtb_cantidad.setText("");
        jtb_idBusc.setText("");
    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            lPan func = new lPan();
            modelo = func.mostrar(buscar);

            jtable_pan.setModel(modelo);
            jlab_registros.setText(Integer.toString(func.totalregistros));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtb_nombre = new javax.swing.JTextField();
        jtb_clase = new javax.swing.JTextField();
        jbot_guardar = new javax.swing.JButton();
        jbot_cancelar = new javax.swing.JButton();
        jbot_nuevo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtb_cantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtb_id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_pan = new javax.swing.JTable();
        jbot_eliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtb_idBusc = new javax.swing.JTextField();
        jbot_salir = new javax.swing.JButton();
        jbot_buscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jlab_registros = new javax.swing.JLabel();
        jbot_actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel1.setText("Pan");

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Pan"));

        jLabel4.setText("Nombre del Pan:");

        jLabel6.setText("Clase:");

        jtb_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_nombreActionPerformed(evt);
            }
        });

        jtb_clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_claseActionPerformed(evt);
            }
        });

        jbot_guardar.setText("Guardar");
        jbot_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_guardarActionPerformed(evt);
            }
        });

        jbot_cancelar.setText("Cancelar");
        jbot_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_cancelarActionPerformed(evt);
            }
        });

        jbot_nuevo.setText("Nuevo");
        jbot_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_nuevoActionPerformed(evt);
            }
        });

        jLabel7.setText("Cantidad:");

        jtb_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_cantidadActionPerformed(evt);
            }
        });

        jLabel10.setText("ID del Pan:");

        jtb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_clase, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jtb_nombre))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbot_nuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(jbot_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbot_cancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbot_cancelar)
                    .addComponent(jbot_guardar)
                    .addComponent(jbot_nuevo))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Pan"));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jtable_pan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_panMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_pan);

        jbot_eliminar.setText("Eliminar");
        jbot_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_eliminarActionPerformed(evt);
            }
        });

        jLabel8.setText("Buscar por ID de Pan:");

        jbot_salir.setText("Salir");
        jbot_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_salirActionPerformed(evt);
            }
        });

        jbot_buscar.setText("Buscar");
        jbot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_buscarActionPerformed(evt);
            }
        });

        jLabel9.setText("Total de registros:");

        jbot_actualizar.setText("Actualizar");
        jbot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlab_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtb_idBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jbot_buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbot_actualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbot_eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbot_salir)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtb_idBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbot_buscar)
                    .addComponent(jbot_actualizar)
                    .addComponent(jbot_eliminar)
                    .addComponent(jbot_salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jlab_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_nombreActionPerformed
        jtb_nombre.transferFocus();
    }//GEN-LAST:event_jtb_nombreActionPerformed

    private void jtb_claseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_claseActionPerformed
        jtb_clase.transferFocus();
    }//GEN-LAST:event_jtb_claseActionPerformed

    private void jbot_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_guardarActionPerformed

        if (jtb_cantidad.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar ID");
            jtb_id.requestFocus();
            return;
        }

        if (jtb_nombre.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un nombre");
            jtb_nombre.requestFocus();
            return;
        }

        if (jtb_clase.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una clase");
            jtb_clase.requestFocus();
            return;
        }

        if (jtb_cantidad.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una cantidad");
            jtb_cantidad.requestFocus();
            return;
        }

        dPan dts = new dPan();
        lPan func = new lPan();

        dts.setId_pan(Integer.parseInt(jtb_id.getText()));
        dts.setNombre(jtb_nombre.getText());
        dts.setClase(jtb_clase.getText());
        dts.setCantidad(Integer.parseInt(jtb_cantidad.getText()));

        if (accion.equals("Guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El Pan fue registrado satisfactoriamente");
                mostrar("");
                habilitar();
            }

        } else if (accion.equals("Actualizar")) {
            dts.setId_pan(Integer.parseInt(jtb_id.getText()));

            if (func.actualizar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El Pan fue actualizado satisfactoriamente");
                mostrar("");
                habilitar();
            }
        }
        jbot_guardar.setText("Guardar");
        accion = "Guardar";
    }//GEN-LAST:event_jbot_guardarActionPerformed

    private void jbot_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_cancelarActionPerformed
        habilitar();
    }//GEN-LAST:event_jbot_cancelarActionPerformed

    private void jbot_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_nuevoActionPerformed
        habilitar();
        jbot_guardar.setText("Guardar");
        accion = "Guardar";
    }//GEN-LAST:event_jbot_nuevoActionPerformed

    private void jtb_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_cantidadActionPerformed

    private void jtb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_idActionPerformed

    private void jtable_panMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_panMouseClicked
        jbot_guardar.setText("Actualizar");
        habilitar();
        accion = "Actualizar";

        int fila = jtable_pan.rowAtPoint(evt.getPoint());

        jtb_id.setText(jtable_pan.getValueAt(fila, 0).toString());
        jtb_nombre.setText(jtable_pan.getValueAt(fila, 1).toString());
        jtb_clase.setText(jtable_pan.getValueAt(fila, 3).toString());
        jtb_cantidad.setText(jtable_pan.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_jtable_panMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked

    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jbot_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_eliminarActionPerformed
        if (!jtb_idBusc.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane,
                    "Estás seguro de Eliminar el Registro " + jtb_idBusc.getText()
                    + " ?", "Confirmar", 2);

            if (confirmacion == 0) {
                dPan dts = new dPan();
                lPan func = new lPan();

                dts.setId_pan(Integer.parseInt(jtb_idBusc.getText()));
                func.eliminar(dts);
                mostrar("");
                habilitar();
            }
        }
    }//GEN-LAST:event_jbot_eliminarActionPerformed

    private void jbot_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbot_salirActionPerformed

    private void jbot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_buscarActionPerformed
        mostrar(jtb_idBusc.getText());
    }//GEN-LAST:event_jbot_buscarActionPerformed

    private void jbot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_actualizarActionPerformed
        mostrar("");
        habilitar();
    }//GEN-LAST:event_jbot_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fEmpleados().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbot_actualizar;
    private javax.swing.JButton jbot_buscar;
    private javax.swing.JButton jbot_cancelar;
    private javax.swing.JButton jbot_eliminar;
    private javax.swing.JButton jbot_guardar;
    private javax.swing.JButton jbot_nuevo;
    private javax.swing.JButton jbot_salir;
    private javax.swing.JLabel jlab_registros;
    private javax.swing.JTable jtable_pan;
    private javax.swing.JTextField jtb_cantidad;
    private javax.swing.JTextField jtb_clase;
    private javax.swing.JTextField jtb_id;
    private javax.swing.JTextField jtb_idBusc;
    private javax.swing.JTextField jtb_nombre;
    // End of variables declaration//GEN-END:variables
}
