/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Datos.dPedidos;
import Logica.lClientes;
import Logica.lEmpleados;
import Logica.lPedidos;
import Logica.lRepartidor;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando
 */
public class fPedidos extends javax.swing.JFrame {

    /**
     * Creates new form fPedidos
     */
    public fPedidos() {
        initComponents();
        mostrar("");
        this.setTitle("Pedidos");
        habilitar();
        //pone la ventana en el Centro de la pantalla
        setLocationRelativeTo(null);
        setDefaultCloseOperation(fPrincipal.ICONIFIED);
        jtb_id.setEnabled(false);
    }
    
    private String accion = "Guardar";
    
    void inhabilitar() {
        jtb_id.setVisible(false);
        jtb_nombre.setVisible(false);
        jtb_idClient.setVisible(false);
        jtb_cliente.setVisible(false);
        jtb_IDRepart.setVisible(false);
        jtb_repart.setVisible(false);
        jtb_azuc.setVisible(false);
        jtb_int.setVisible(false);
        jtb_fran.setVisible(false);
        jtb_total.setVisible(false);
        jtb_fecha.setVisible(false);

        jbot_nuevo.setEnabled(false);
        jbot_guardar.setEnabled(false);
        jbot_cancelar.setEnabled(false);
    }

    void habilitar() {
        jtb_id.setVisible(true);
        jtb_nombre.setVisible(true);
        jtb_idClient.setVisible(true);
        jtb_cliente.setVisible(true);
        jtb_IDRepart.setVisible(true);
        jtb_repart.setVisible(true);
        jtb_azuc.setVisible(true);
        jtb_int.setVisible(true);
        jtb_fran.setVisible(true);
        jtb_total.setVisible(true);
        jtb_fecha.setVisible(true);

        jbot_nuevo.setEnabled(true);
        jbot_guardar.setEnabled(true);
        jbot_cancelar.setEnabled(true);
        jtb_id.setText("");
        jtb_nombre.setText("");
        jtb_idClient.setText("");
        jtb_cliente.setText("");
        jtb_IDRepart.setText("");
        jtb_repart.setText("");
        jtb_azuc.setText("");
        jtb_int.setText("");
        jtb_fran.setText("");
        jtb_total.setText("");
        jtb_fecha.setText("");
        jtb_idBusc.setText("");
    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            lPedidos func = new lPedidos();
            modelo = func.mostrar(buscar);

            jtable_pedido.setModel(modelo);
            jlab_registros.setText(Integer.toString(func.totalregistros));
            
            
            DefaultTableModel modelo2;
            lRepartidor func2 = new lRepartidor();
            modelo2 = func2.mostrar2(buscar);

            jTable_repar.setModel(modelo2);
            
            
            DefaultTableModel modelo3;
            lClientes func3 = new lClientes();
            modelo3 = func3.mostrar2(buscar);

            jTable_client.setModel(modelo3);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtb_nombre = new javax.swing.JTextField();
        jtb_idClient = new javax.swing.JTextField();
        jtb_IDRepart = new javax.swing.JTextField();
        jbot_guardar = new javax.swing.JButton();
        jbot_cancelar = new javax.swing.JButton();
        jbot_nuevo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtb_repart = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtb_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtb_azuc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtb_int = new javax.swing.JTextField();
        jtb_cliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtb_fran = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtb_total = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtb_fecha = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_pedido = new javax.swing.JTable();
        jbot_eliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtb_idBusc = new javax.swing.JTextField();
        jbot_salir = new javax.swing.JButton();
        jbot_buscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jlab_registros = new javax.swing.JLabel();
        jbot_actualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_repar = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_client = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel1.setText("Pedidos");

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Pedidos"));

        jLabel4.setText("Nombre del Pedido:");

        jLabel5.setText("ID del Cliente");

        jLabel6.setText("ID del Repartidor:");

        jtb_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_nombreActionPerformed(evt);
            }
        });

        jtb_idClient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtb_idClientFocusLost(evt);
            }
        });
        jtb_idClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_idClientActionPerformed(evt);
            }
        });

        jtb_IDRepart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtb_IDRepartFocusLost(evt);
            }
        });
        jtb_IDRepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_IDRepartActionPerformed(evt);
            }
        });

        jbot_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/guardar.png"))); // NOI18N
        jbot_guardar.setText("Guardar");
        jbot_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_guardarActionPerformed(evt);
            }
        });

        jbot_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cancelar.png"))); // NOI18N
        jbot_cancelar.setText("Cancelar");
        jbot_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_cancelarActionPerformed(evt);
            }
        });

        jbot_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/page.png"))); // NOI18N
        jbot_nuevo.setText("Nuevo");
        jbot_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_nuevoActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre del Repartidor:");

        jtb_repart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtb_repartFocusLost(evt);
            }
        });
        jtb_repart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_repartActionPerformed(evt);
            }
        });

        jLabel10.setText("ID del Pedido:");

        jtb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_idActionPerformed(evt);
            }
        });

        jLabel11.setText("Cantidad de Azucar:");

        jtb_azuc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtb_azucFocusLost(evt);
            }
        });
        jtb_azuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_azucActionPerformed(evt);
            }
        });

        jLabel12.setText("Cantidad de Ingegral:");

        jtb_int.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtb_intFocusLost(evt);
            }
        });
        jtb_int.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_intActionPerformed(evt);
            }
        });

        jtb_cliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtb_clienteFocusGained(evt);
            }
        });
        jtb_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_clienteActionPerformed(evt);
            }
        });

        jLabel13.setText("Nombre del Cliente:");

        jtb_fran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtb_franFocusLost(evt);
            }
        });
        jtb_fran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_franActionPerformed(evt);
            }
        });

        jLabel14.setText("Cantidad de Frances:");

        jtb_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_totalActionPerformed(evt);
            }
        });

        jLabel15.setText("Cantidad Total:");

        jtb_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_fechaActionPerformed(evt);
            }
        });

        jLabel16.setText("Fecha del pedido:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_repart, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtb_idClient, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jtb_nombre))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbot_nuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(jbot_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbot_cancelar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_azuc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_int, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_IDRepart, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_fran, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtb_idClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_IDRepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_repart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_azuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_fran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbot_cancelar)
                    .addComponent(jbot_guardar)
                    .addComponent(jbot_nuevo))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Pedidos"));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jtable_pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_pedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_pedidoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_pedido);

        jbot_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/eliminar.png"))); // NOI18N
        jbot_eliminar.setText("Eliminar");
        jbot_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_eliminarActionPerformed(evt);
            }
        });

        jLabel8.setText("Buscar por ID de Pedido:");

        jbot_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/home.png"))); // NOI18N
        jbot_salir.setText("Salir");
        jbot_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_salirActionPerformed(evt);
            }
        });

        jbot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/search.png"))); // NOI18N
        jbot_buscar.setText("Buscar");
        jbot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_buscarActionPerformed(evt);
            }
        });

        jLabel9.setText("Total de registros:");

        jbot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/clock.png"))); // NOI18N
        jbot_actualizar.setText("Actualizar");
        jbot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_actualizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Repartidores:");

        jLabel3.setText("Clientes:");

        jTable_repar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_repar);

        jTable_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable_client);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb_idBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jbot_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jbot_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbot_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbot_salir))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlab_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtb_idBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbot_buscar)
                    .addComponent(jbot_actualizar)
                    .addComponent(jbot_eliminar)
                    .addComponent(jbot_salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addComponent(jlab_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_nombreActionPerformed
        jtb_nombre.transferFocus();
    }//GEN-LAST:event_jtb_nombreActionPerformed

    private void jtb_idClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_idClientActionPerformed
        jtb_idClient.transferFocus();
    }//GEN-LAST:event_jtb_idClientActionPerformed

    private void jtb_IDRepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_IDRepartActionPerformed
        jtb_IDRepart.transferFocus();
    }//GEN-LAST:event_jtb_IDRepartActionPerformed

    private void jbot_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_guardarActionPerformed

        if (jtb_nombre.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un nombre al pedido");
            jtb_nombre.requestFocus();
            return;
        }

        if (jtb_idClient.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un ID de Cliente");
            jtb_idClient.requestFocus();
            return;
        }
        
        if (jtb_cliente.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar el nombre del cliente");
            jtb_cliente.requestFocus();
            return;
        }

        if (jtb_IDRepart.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un ID de repartidor");
            jtb_IDRepart.requestFocus();
            return;
        }

        if (jtb_repart.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar el nombre del repartidor");
            jtb_repart.requestFocus();
            return;
        }

        if (jtb_fecha.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una fecha");
            jtb_fecha.requestFocus();
            return;
        }

        if (jtb_azuc.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una cantidad de azucar");
            jtb_azuc.requestFocus();
            return;
        }
        
        if (jtb_int.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una cantidad de integral");
            jtb_int.requestFocus();
            return;
        }
        
        if (jtb_fran.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una cantidad de frances");
            jtb_fran.requestFocus();
            return;
        }
        
        if (jtb_total.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una cantidad total");
            jtb_total.requestFocus();
            return;
        }

        dPedidos dts = new dPedidos();
        lPedidos func = new lPedidos();

        dts.setNombre(jtb_nombre.getText());
        dts.setNumClient(Integer.parseInt(jtb_idClient.getText()));
        dts.setCliente(jtb_cliente.getText());
        dts.setNumRepart(Integer.parseInt(jtb_IDRepart.getText()));
        dts.setRepartidor(jtb_repart.getText());
        dts.setFecha(jtb_fecha.getText());
        dts.setCant_azuc(Integer.parseInt(jtb_azuc.getText()));
        dts.setCant_integ(Integer.parseInt(jtb_int.getText()));
        dts.setCant_fran(Integer.parseInt(jtb_fran.getText()));
        dts.setCant_total(Integer.parseInt(jtb_total.getText()));

        if (accion.equals("Guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El Pedido fue registrado satisfactoriamente");
                mostrar("");
                habilitar();
            }

        } else if (accion.equals("Actualizar")) {
            dts.setId_pedido(Integer.parseInt(jtb_id.getText()));

            if (func.actualizar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El Pedido fue actualizado satisfactoriamente");
                mostrar("");
                habilitar();
            }
        }
        jbot_guardar.setText("Guardar");
        accion = "Guardar";
    }//GEN-LAST:event_jbot_guardarActionPerformed

    private void jbot_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_cancelarActionPerformed
        habilitar();
    }//GEN-LAST:event_jbot_cancelarActionPerformed

    private void jbot_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_nuevoActionPerformed
        habilitar();
        jbot_guardar.setText("Guardar");
        accion = "Guardar";
    }//GEN-LAST:event_jbot_nuevoActionPerformed

    private void jtb_repartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_repartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_repartActionPerformed

    private void jtb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_idActionPerformed

    private void jtb_azucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_azucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_azucActionPerformed

    private void jtb_intActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_intActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_intActionPerformed

    private void jtable_pedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_pedidoMouseClicked
        jbot_guardar.setText("Actualizar");
        habilitar();
        accion = "Actualizar";

        int fila = jtable_pedido.rowAtPoint(evt.getPoint());

        jtb_id.setText(jtable_pedido.getValueAt(fila, 0).toString());
        jtb_nombre.setText(jtable_pedido.getValueAt(fila, 1).toString());
        jtb_idClient.setText(jtable_pedido.getValueAt(fila, 2).toString());
        jtb_cliente.setText(jtable_pedido.getValueAt(fila, 3).toString());
        jtb_IDRepart.setText(jtable_pedido.getValueAt(fila, 4).toString());
        jtb_repart.setText(jtable_pedido.getValueAt(fila, 5).toString());
        jtb_fecha.setText(jtable_pedido.getValueAt(fila, 6).toString());
        jtb_azuc.setText(jtable_pedido.getValueAt(fila, 7).toString());
        jtb_int.setText(jtable_pedido.getValueAt(fila, 8).toString());
        jtb_fran.setText(jtable_pedido.getValueAt(fila, 9).toString());
        jtb_total.setText(jtable_pedido.getValueAt(fila, 10).toString());
    }//GEN-LAST:event_jtable_pedidoMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked

    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jbot_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_eliminarActionPerformed
        if (!jtb_id.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane,
                "Estás seguro de Eliminar el Pedido " + jtb_id.getText()
                + " ?", "Confirmar", 2);

            if (confirmacion == 0) {
                dPedidos dts = new dPedidos();
                lPedidos func = new lPedidos();

                dts.setId_pedido(Integer.parseInt(jtb_id.getText()));
                func.eliminar(dts);
                mostrar("");
                habilitar();
            }
            
            jbot_guardar.setText("Guardar");
            accion = "Guardar";
        }
    }//GEN-LAST:event_jbot_eliminarActionPerformed

    private void jbot_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbot_salirActionPerformed

    private void jbot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_buscarActionPerformed
        mostrar(jtb_idBusc.getText());
    }//GEN-LAST:event_jbot_buscarActionPerformed

    private void jbot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_actualizarActionPerformed
        mostrar("");
        habilitar();
    }//GEN-LAST:event_jbot_actualizarActionPerformed

    private void jtb_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_clienteActionPerformed

    private void jtb_franActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_franActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_franActionPerformed

    private void jtb_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_totalActionPerformed

    private void jtb_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_fechaActionPerformed

    private void jtb_franFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtb_franFocusLost
        
        int total = Integer.parseInt(jtb_int.getText()) 
                + Integer.parseInt(jtb_azuc.getText()) 
                + Integer.parseInt(jtb_fran.getText());
        
        jtb_total.setText(total + "");
    }//GEN-LAST:event_jtb_franFocusLost

    private void jtb_azucFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtb_azucFocusLost
        int total = Integer.parseInt(jtb_int.getText()) 
                + Integer.parseInt(jtb_azuc.getText()) 
                + Integer.parseInt(jtb_fran.getText());
        
        jtb_total.setText(total + "");
    }//GEN-LAST:event_jtb_azucFocusLost

    private void jtb_intFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtb_intFocusLost
        int total = Integer.parseInt(jtb_int.getText()) 
                + Integer.parseInt(jtb_azuc.getText()) 
                + Integer.parseInt(jtb_fran.getText());
        
        jtb_total.setText(total + "");
    }//GEN-LAST:event_jtb_intFocusLost

    private void jtb_idClientFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtb_idClientFocusLost
        
        int fila = jTable_client.getRowCount();
        int pos = Integer.parseInt(jtb_idClient.getText());
        boolean band = false;
        
        for (int i = 0; i < jTable_client.getRowCount(); i++){
            if (pos == Integer.parseInt(jTable_client.getValueAt(i, 0).toString())){
                jtb_cliente.setText(jTable_client.getValueAt(i, 1).toString());
                band = true;
            }
        }
        
        if (!band){
            JOptionPane.showMessageDialog(rootPane, "El id no coincide con ningun repartidor");
            jtb_cliente.setText("");
            jtb_idClient.setText("");
            jtb_cliente.transferFocusBackward();
        }
        
    }//GEN-LAST:event_jtb_idClientFocusLost

    private void jtb_clienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtb_clienteFocusGained
        
    }//GEN-LAST:event_jtb_clienteFocusGained

    private void jtb_IDRepartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtb_IDRepartFocusLost
        int fila = jTable_repar.getRowCount();
        int pos = Integer.parseInt(jtb_IDRepart.getText());
        boolean band = false;
        
        for (int i = 0; i < jTable_repar.getRowCount(); i++){
            if (pos == Integer.parseInt(jTable_repar.getValueAt(i, 0).toString())){
                jtb_repart.setText(jTable_repar.getValueAt(i, 1).toString());
                band = true;
            }
        }
        
        if (!band){
            JOptionPane.showMessageDialog(rootPane, "El id no coincide con ningun repartidor");
            jtb_repart.setText("");
            jtb_IDRepart.setText("");
            jtb_repart.transferFocusBackward();
        }
            
    }//GEN-LAST:event_jtb_IDRepartFocusLost

    private void jtb_repartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtb_repartFocusLost
        Date myDate = new Date();
        
        String fecha = new SimpleDateFormat("dd-MM-yyyy").format(myDate);
        jtb_fecha.setText(fecha);
    }//GEN-LAST:event_jtb_repartFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_client;
    private javax.swing.JTable jTable_repar;
    private javax.swing.JButton jbot_actualizar;
    private javax.swing.JButton jbot_buscar;
    private javax.swing.JButton jbot_cancelar;
    private javax.swing.JButton jbot_eliminar;
    private javax.swing.JButton jbot_guardar;
    private javax.swing.JButton jbot_nuevo;
    private javax.swing.JButton jbot_salir;
    private javax.swing.JLabel jlab_registros;
    private javax.swing.JTable jtable_pedido;
    private javax.swing.JTextField jtb_IDRepart;
    private javax.swing.JTextField jtb_azuc;
    private javax.swing.JTextField jtb_cliente;
    private javax.swing.JTextField jtb_fecha;
    private javax.swing.JTextField jtb_fran;
    private javax.swing.JTextField jtb_id;
    private javax.swing.JTextField jtb_idBusc;
    private javax.swing.JTextField jtb_idClient;
    private javax.swing.JTextField jtb_int;
    private javax.swing.JTextField jtb_nombre;
    private javax.swing.JTextField jtb_repart;
    private javax.swing.JTextField jtb_total;
    // End of variables declaration//GEN-END:variables
}
