/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Datos.dRepartidores;
import Logica.lEmpleados;
import Logica.lRepartidor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando
 */
public class fRepartidores extends javax.swing.JFrame {

    /**
     * Creates new form fRepartidores
     */
    public fRepartidores() {
        initComponents();
        mostrar("");
        this.setTitle("Repartidores");
        habilitar();
        //pone la ventana en el Centro de la pantalla
        setLocationRelativeTo(null);
        setDefaultCloseOperation(fPrincipal.ICONIFIED);
        jtb_id.setEnabled(false);
    }
    
    private String accion = "Guardar";
    
    void inhabilitar() {
        jtb_id.setVisible(false);
        jtb_nombre.setVisible(false);
        jtb_direccion.setVisible(false);
        jtb_telefono.setVisible(false);
        jtb_edad.setVisible(false);
        jtb_tipo.setVisible(false);

        jbot_nuevo.setEnabled(false);
        jbot_guardar.setEnabled(false);
        jbot_cancelar.setEnabled(false);
    }

    void habilitar() {
        jtb_id.setVisible(true);
        jtb_nombre.setVisible(true);
        jtb_direccion.setVisible(true);
        jtb_telefono.setVisible(true);
        jtb_edad.setVisible(true);
        jtb_tipo.setVisible(true);

        jbot_nuevo.setEnabled(true);
        jbot_guardar.setEnabled(true);
        jbot_cancelar.setEnabled(true);
        jtb_id.setText("");
        jtb_nombre.setText("");
        jtb_direccion.setText("");
        jtb_telefono.setText("");
        jtb_edad.setText("");
        jtb_tipo.setText("");
        jtb_idBusc.setText("");
    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            lRepartidor func = new lRepartidor();
            modelo = func.mostrar(buscar);

            jtable_repart.setModel(modelo);
            jlab_registros.setText(Integer.toString(func.totalregistros));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtb_nombre = new javax.swing.JTextField();
        jtb_direccion = new javax.swing.JTextField();
        jtb_telefono = new javax.swing.JTextField();
        jbot_guardar = new javax.swing.JButton();
        jbot_cancelar = new javax.swing.JButton();
        jbot_nuevo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtb_edad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtb_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtb_tipo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_repart = new javax.swing.JTable();
        jbot_eliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtb_idBusc = new javax.swing.JTextField();
        jbot_salir = new javax.swing.JButton();
        jbot_buscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jlab_registros = new javax.swing.JLabel();
        jbot_actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel1.setText("Repartidores");

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Repartidores"));

        jLabel4.setText("Nombre del Repartidor:");

        jLabel5.setText("Direccion");

        jLabel6.setText("Telefono:");

        jtb_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_nombreActionPerformed(evt);
            }
        });

        jtb_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_direccionActionPerformed(evt);
            }
        });

        jtb_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_telefonoActionPerformed(evt);
            }
        });

        jbot_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/guardar.png"))); // NOI18N
        jbot_guardar.setText("Guardar");
        jbot_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_guardarActionPerformed(evt);
            }
        });

        jbot_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cancelar.png"))); // NOI18N
        jbot_cancelar.setText("Cancelar");
        jbot_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_cancelarActionPerformed(evt);
            }
        });

        jbot_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/page.png"))); // NOI18N
        jbot_nuevo.setText("Nuevo");
        jbot_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_nuevoActionPerformed(evt);
            }
        });

        jLabel7.setText("Edad:");

        jtb_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_edadActionPerformed(evt);
            }
        });

        jLabel10.setText("ID del Repartidor:");

        jtb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_idActionPerformed(evt);
            }
        });

        jLabel11.setText("Tipo:");

        jtb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_tipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtb_direccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jtb_nombre))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbot_nuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(jbot_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbot_cancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtb_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbot_cancelar)
                    .addComponent(jbot_guardar)
                    .addComponent(jbot_nuevo))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Repartidores"));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jtable_repart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_repart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_repartMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_repart);

        jbot_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/eliminar.png"))); // NOI18N
        jbot_eliminar.setText("Eliminar");
        jbot_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_eliminarActionPerformed(evt);
            }
        });

        jLabel8.setText("Buscar por ID de Repartidor:");

        jbot_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/home.png"))); // NOI18N
        jbot_salir.setText("Salir");
        jbot_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_salirActionPerformed(evt);
            }
        });

        jbot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/buscar.png"))); // NOI18N
        jbot_buscar.setText("Buscar");
        jbot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_buscarActionPerformed(evt);
            }
        });

        jLabel9.setText("Total de registros:");

        jbot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/clock.png"))); // NOI18N
        jbot_actualizar.setText("Actualizar");
        jbot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlab_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtb_idBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jbot_buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbot_actualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbot_eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbot_salir)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtb_idBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbot_buscar)
                    .addComponent(jbot_actualizar)
                    .addComponent(jbot_eliminar)
                    .addComponent(jbot_salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jlab_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_nombreActionPerformed
        jtb_nombre.transferFocus();
    }//GEN-LAST:event_jtb_nombreActionPerformed

    private void jtb_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_direccionActionPerformed
        jtb_direccion.transferFocus();
    }//GEN-LAST:event_jtb_direccionActionPerformed

    private void jtb_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_telefonoActionPerformed
        jtb_telefono.transferFocus();
    }//GEN-LAST:event_jtb_telefonoActionPerformed

    private void jbot_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_guardarActionPerformed

        if (jtb_nombre.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un nombre");
            jtb_nombre.requestFocus();
            return;
        }

        if (jtb_direccion.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una direccion");
            jtb_direccion.requestFocus();
            return;
        }

        if (jtb_telefono.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un telefono");
            jtb_telefono.requestFocus();
            return;
        }

        if (jtb_edad.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una edad");
            jtb_edad.requestFocus();
            return;
        }

        if (jtb_tipo.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un tipo");
            jtb_tipo.requestFocus();
            return;
        }

        dRepartidores dts = new dRepartidores();
        lRepartidor func = new lRepartidor();

        dts.setNombre(jtb_nombre.getText());
        dts.setDireccion(jtb_direccion.getText());
        dts.setTelefono(jtb_telefono.getText());
        dts.setEdad(jtb_edad.getText());
        dts.setTipo(Integer.parseInt(jtb_tipo.getText()));

        if (accion.equals("Guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El Repartidor fue registrado satisfactoriamente");
                mostrar("");
                habilitar();
            }

        } else if (accion.equals("Actualizar")) {
            dts.setId_repart(Integer.parseInt(jtb_id.getText()));

            if (func.actualizar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El Repartidor fue actualizado satisfactoriamente");
                mostrar("");
                habilitar();
            }
        }
        jbot_guardar.setText("Guardar");
        accion = "Guardar";
    }//GEN-LAST:event_jbot_guardarActionPerformed

    private void jbot_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_cancelarActionPerformed
        habilitar();
    }//GEN-LAST:event_jbot_cancelarActionPerformed

    private void jbot_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_nuevoActionPerformed
        habilitar();
        jbot_guardar.setText("Guardar");
        accion = "Guardar";
    }//GEN-LAST:event_jbot_nuevoActionPerformed

    private void jtb_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_edadActionPerformed

    private void jtb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_idActionPerformed

    private void jtb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_tipoActionPerformed

    private void jtable_repartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_repartMouseClicked
        jbot_guardar.setText("Actualizar");
        habilitar();
        accion = "Actualizar";

        int fila = jtable_repart.rowAtPoint(evt.getPoint());

        jtb_id.setText(jtable_repart.getValueAt(fila, 0).toString());
        jtb_nombre.setText(jtable_repart.getValueAt(fila, 1).toString());
        jtb_direccion.setText(jtable_repart.getValueAt(fila, 2).toString());
        jtb_telefono.setText(jtable_repart.getValueAt(fila, 3).toString());
        jtb_edad.setText(jtable_repart.getValueAt(fila, 4).toString());
        jtb_tipo.setText(jtable_repart.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_jtable_repartMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked

    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jbot_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_eliminarActionPerformed
        if (!jtb_id.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane,
                "Estás seguro de Eliminar el repartidor " + jtb_id.getText()
                + " ?", "Confirmar", 2);

            if (confirmacion == 0) {
                dRepartidores dts = new dRepartidores();
                lRepartidor func = new lRepartidor();

                dts.setId_repart(Integer.parseInt(jtb_id.getText()));
                func.eliminar(dts);
                mostrar("");
                habilitar();
            }
            
            jbot_guardar.setText("Guardar");
            accion = "Guardar";
        }
    }//GEN-LAST:event_jbot_eliminarActionPerformed

    private void jbot_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbot_salirActionPerformed

    private void jbot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_buscarActionPerformed
        mostrar(jtb_idBusc.getText());
    }//GEN-LAST:event_jbot_buscarActionPerformed

    private void jbot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_actualizarActionPerformed
        mostrar("");
        habilitar();
    }//GEN-LAST:event_jbot_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fRepartidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fRepartidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fRepartidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fRepartidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fRepartidores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbot_actualizar;
    private javax.swing.JButton jbot_buscar;
    private javax.swing.JButton jbot_cancelar;
    private javax.swing.JButton jbot_eliminar;
    private javax.swing.JButton jbot_guardar;
    private javax.swing.JButton jbot_nuevo;
    private javax.swing.JButton jbot_salir;
    private javax.swing.JLabel jlab_registros;
    private javax.swing.JTable jtable_repart;
    private javax.swing.JTextField jtb_direccion;
    private javax.swing.JTextField jtb_edad;
    private javax.swing.JTextField jtb_id;
    private javax.swing.JTextField jtb_idBusc;
    private javax.swing.JTextField jtb_nombre;
    private javax.swing.JTextField jtb_telefono;
    private javax.swing.JTextField jtb_tipo;
    // End of variables declaration//GEN-END:variables
}
