/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Datos.dUsuarios;
import Logica.lUsuarios;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armando
 */
public class fUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form fUsuarios
     */
    public fUsuarios() {
        initComponents();
        mostrar("");
        this.setTitle("Usuarios");
        habilitar();
        //pone la ventana en el Centro de la pantalla
        setLocationRelativeTo(null);
        setDefaultCloseOperation(fPrincipal.EXIT_ON_CLOSE);
    }

    private String accion = "Guardar";

    void inhabilitar() {
        jtb_id.setVisible(false);
        jtb_nombre3.setVisible(false);
        jtb_contra.setVisible(false);
        jtb_ingreso.setVisible(false);

        jbot_nuevo.setEnabled(false);
        jbot_guardar.setEnabled(false);
        jbot_cancelar.setEnabled(false);
    }

    void habilitar() {
        jtb_id.setVisible(true);
        jtb_nombre3.setVisible(true);
        jtb_contra.setVisible(true);
        jtb_ingreso.setVisible(true);

        jbot_nuevo.setEnabled(true);
        jbot_guardar.setEnabled(true);
        jbot_cancelar.setEnabled(true);
        jtb_id.setText("");
        jtb_nombre3.setText("");
        jtb_contra.setText("");
        jtb_ingreso.setText("");
        jtb_idBusc.setText("");
    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            lUsuarios func = new lUsuarios();
            modelo = func.mostrar(buscar);

            jtable_usuarios.setModel(modelo);
            jlab_registros.setText(Integer.toString(func.totalregistros));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtb_nombre3 = new javax.swing.JTextField();
        jtb_contra = new javax.swing.JTextField();
        jbot_guardar = new javax.swing.JButton();
        jbot_cancelar = new javax.swing.JButton();
        jbot_nuevo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtb_ingreso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtb_id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_usuarios = new javax.swing.JTable();
        jbot_eliminar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jtb_idBusc = new javax.swing.JTextField();
        jbot_salir = new javax.swing.JButton();
        jbot_buscar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jlab_registros = new javax.swing.JLabel();
        jbot_actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel1.setText("Usuarios");

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Usuarios"));

        jLabel10.setText("Nombre del Usuario:");

        jLabel11.setText("Contrasena:");

        jtb_nombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_nombre3ActionPerformed(evt);
            }
        });

        jtb_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_contraActionPerformed(evt);
            }
        });

        jbot_guardar.setText("Guardar");
        jbot_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_guardarActionPerformed(evt);
            }
        });

        jbot_cancelar.setText("Cancelar");
        jbot_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_cancelarActionPerformed(evt);
            }
        });

        jbot_nuevo.setText("Nuevo");
        jbot_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_nuevoActionPerformed(evt);
            }
        });

        jLabel12.setText("Fecha de Ingreso:");

        jtb_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_ingresoActionPerformed(evt);
            }
        });

        jLabel13.setText("ID del Usuario:");

        jtb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jbot_nuevo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                    .addComponent(jbot_guardar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jbot_cancelar))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtb_nombre3)
                                        .addComponent(jtb_contra)
                                        .addComponent(jtb_ingreso, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbot_cancelar)
                    .addComponent(jbot_guardar)
                    .addComponent(jbot_nuevo))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Usuarios"));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jtable_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_usuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_usuarios);

        jbot_eliminar.setText("Eliminar");
        jbot_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_eliminarActionPerformed(evt);
            }
        });

        jLabel14.setText("Buscar por ID de Pan:");

        jbot_salir.setText("Salir");
        jbot_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_salirActionPerformed(evt);
            }
        });

        jbot_buscar.setText("Buscar");
        jbot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_buscarActionPerformed(evt);
            }
        });

        jLabel15.setText("Total de registros:");

        jbot_actualizar.setText("Actualizar");
        jbot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbot_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlab_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtb_idBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jbot_buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbot_actualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbot_eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbot_salir)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtb_idBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbot_buscar)
                    .addComponent(jbot_actualizar)
                    .addComponent(jbot_eliminar)
                    .addComponent(jbot_salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jlab_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_nombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_nombre3ActionPerformed
        jtb_nombre.transferFocus();
    }//GEN-LAST:event_jtb_nombre3ActionPerformed

    private void jtb_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_contraActionPerformed
        jtb_contra.transferFocus();
    }//GEN-LAST:event_jtb_contraActionPerformed

    private void jbot_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_guardarActionPerformed

        if (jtb_id.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar ID");
            jtb_id.requestFocus();
            return;
        }

        if (jtb_nombre3.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un nombre");
            jtb_nombre.requestFocus();
            return;
        }

        if (jtb_contra.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una contrasena");
            jtb_contra.requestFocus();
            return;
        }

        if (jtb_ingreso.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una fecha de ingreso");
            jtb_ingreso.requestFocus();
            return;
        }

        dUsuarios dts = new dUsuarios();
        lUsuarios func = new lUsuarios();

        dts.setId_usuarios(Integer.parseInt(jtb_id.getText()));
        dts.setUsuario(jtb_nombre3.getText());
        dts.setContra(jtb_contra.getText());
        dts.setFechaIngreso(jtb_ingreso.getText());

        if (accion.equals("Guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El Usuario fue registrado satisfactoriamente");
                mostrar("");
                habilitar();
            }

        } else if (accion.equals("Actualizar")) {
            dts.setId_usuarios(Integer.parseInt(jtb_id.getText()));

            if (func.actualizar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El Usuario fue actualizado satisfactoriamente");
                mostrar("");
                habilitar();
            }
        }
        jbot_guardar.setText("Guardar");
        accion = "Guardar";
    }//GEN-LAST:event_jbot_guardarActionPerformed

    private void jbot_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_cancelarActionPerformed
        habilitar();
    }//GEN-LAST:event_jbot_cancelarActionPerformed

    private void jbot_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_nuevoActionPerformed
        habilitar();
        jbot_guardar.setText("Guardar");
        accion = "Guardar";
    }//GEN-LAST:event_jbot_nuevoActionPerformed

    private void jtb_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_ingresoActionPerformed

    private void jtb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_idActionPerformed

    private void jtable_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_usuariosMouseClicked
        jbot_guardar.setText("Actualizar");
        habilitar();
        accion = "Actualizar";

        int fila = jtable_usuarios.rowAtPoint(evt.getPoint());

        jtb_id.setText(jtable_usuarios.getValueAt(fila, 0).toString());
        jtb_nombre3.setText(jtable_usuarios.getValueAt(fila, 1).toString());
        jtb_contra.setText(jtable_usuarios.getValueAt(fila, 3).toString());
        jtb_ingreso.setText(jtable_usuarios.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_jtable_usuariosMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked

    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jbot_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_eliminarActionPerformed
        if (!jtb_idBusc.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane,
                "Estás seguro de Eliminar el Registro " + jtb_idBusc.getText()
                + " ?", "Confirmar", 2);

            if (confirmacion == 0) {
                dUsuarios dts = new dUsuarios();
                lUsuarios func = new lUsuarios();

                dts.setId_usuarios(Integer.parseInt(jtb_idBusc.getText()));
                func.eliminar(dts);
                mostrar("");
                habilitar();
            }
        }
    }//GEN-LAST:event_jbot_eliminarActionPerformed

    private void jbot_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbot_salirActionPerformed

    private void jbot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_buscarActionPerformed
        mostrar(jtb_idBusc.getText());
    }//GEN-LAST:event_jbot_buscarActionPerformed

    private void jbot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbot_actualizarActionPerformed
        mostrar("");
        habilitar();
    }//GEN-LAST:event_jbot_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbot_actualizar;
    private javax.swing.JButton jbot_buscar;
    private javax.swing.JButton jbot_cancelar;
    private javax.swing.JButton jbot_eliminar;
    private javax.swing.JButton jbot_guardar;
    private javax.swing.JButton jbot_nuevo;
    private javax.swing.JButton jbot_salir;
    private javax.swing.JLabel jlab_registros;
    private javax.swing.JTable jtable_usuarios;
    private javax.swing.JTextField jtb_contra;
    private javax.swing.JTextField jtb_id;
    private javax.swing.JTextField jtb_idBusc;
    private javax.swing.JTextField jtb_ingreso;
    private javax.swing.JTextField jtb_nombre;
    private javax.swing.JTextField jtb_nombre1;
    private javax.swing.JTextField jtb_nombre2;
    private javax.swing.JTextField jtb_nombre3;
    // End of variables declaration//GEN-END:variables
}
